### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Joseph-Rance** [maximiseuk/onlinestudytools#35]
~Correct me if i'm wrong, but think (apart from the landing page) to get the website online we only have to:~
 - [x] ~Put the ML code onto Heroku~
 - [x] ~host the website~

~(that might be completely stupid because I really have no idea)~

**Comment by Joseph-Rance** [comment]
New todo list:

(for @KashParty unless otherwise specified)

 - [ ] Add our names on the bottom
 - [ ] Add Ryan and Shannon to meet the team bit
 - [ ] Change image in the phone on the website
 - [ ] Make images on top bit lower resolution
 - [ ] Put icon on the tab at the top
 - [ ] Fix Samsung internet problem
 - [ ] Fix problem with opening goals section @isaacholt100 
 - [ ] Change typeface where it says 'you don't have any goals' @isaacholt100 
 - [ ] Add ML to the server
 - [ ] Do SEO @Joseph-Rance

**Comment by Joseph-Rance** [comment]
Gonna make a new issue to update this list
