### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by Joseph-Rance** [maximiseuk/onlinestudytools#53]
This is the stuff we still have to do to finish the project:

 - [x] Change image in the phone on the website @maximiseuk 
 - [ ] Add ML to the server / make the ml work @maximiseuk & @Joseph-Rance 
 - [x] Do SEO @Joseph-Rance 
 - [x] Get the info from the psychologist for the website @Joseph-Rance 
 - [x] Add a suitable replacement for the "mug" (which is not a plant) in the tools pages @isaacholt100 
 - [ ] Merge and Upload the website @maximiseuk

**Comment by Joseph-Rance** [comment]
@isaacholt100 does the stuff that you put in the timetable actually appear on the homepage?

**Comment by Joseph-Rance** [comment]
list of filenames to add:
![image](https://user-images.githubusercontent.com/56409230/77048604-a15ab300-69be-11ea-93f9-70e85d8f3982.png)

**Comment by Joseph-Rance** [comment]
made updated todo list
