### ISSUE TITLE
Final todo list I promise

### ISSUE THREAD

**Issue by Joseph-Rance** [maximiseuk/onlinestudytools#62]
- [ ] Add quote
 - [ ] Rename files for SEO
 - [ ] Merge into master
 - [ ] Put the website up

**Comment by Joseph-Rance** [comment]
![image](https://user-images.githubusercontent.com/56409230/77820931-d0b7a100-70dd-11ea-8d4d-4e4bb3a6f33f.png)

**Comment by Joseph-Rance** [comment]
(you don't need to add the quote)
![image](https://user-images.githubusercontent.com/56409230/77820939-df05bd00-70dd-11ea-9485-962f042e3187.png)
